allowBuilds:
  '@firebase/util': set this to true or false
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: set this to true or false
  esbuild: true
  prisma: true
  protobufjs: set this to true or false
  unrs-resolver: true
